## This script reads in ASCII rasters generated by RAMAS spatial data and creates a plot

library(tidyverse)
library(terra)
library(tidyterra)
library(patchwork)
library(ggspatial)

# Read in MS shapefile
ms <- vect("data/landscape_data/mississippi_ACEA.shp")

# List patch .asc files
patches <- list.files(path="results/exported_patches/", pattern=".ASC", full.names=TRUE)  # note that the pattern argument is case-sensitive, and RAMAS writes ASCII files as .ASC instead of .asc like R

# Make raster "stack"
patches <- rast(patches)

# Define projection
crs(patches) <- crs(ms)

# # rename because I switched the pig patches
# names(patches) <- c("deer_core","deer_marginal","deer_moderate","pigs_core","pigs_marginal","pigs_moderate")

patches <- patches[[c(1,3,2,4,6,5)]]

# Reclassify so that 0 becomes NA (backround is 0, patches are numbered starting with 1), and all patches receive same class value (1)
# If you want to show different patches, don't do the second part
# Replace 0 with NA
patches <- ifel(patches == 0, NA_integer_, patches)

# Loop over patches and write as .tif
for (i in 1:dim(patches)[3]) {
  # Subset to each layer
  patch <- patches[[i]]
  
  # create filename
  filename <- paste0("results/exported_patches/", names(patch), ".tif")
  
  # write raster
  writeRaster(patch, filename, overwrite=TRUE)
}

# Reclassify all patches as 1
patches <- ifel(patches>=1, 1, patches)

# Convert rasters to polygons
polylist <- lapply(as.list(patches), as.polygons)

# Make a named list so layers can by extracted by name
names(polylist) <- names(patches)

## Calculate area
# Core
expanse(polylist[["deer_core"]], unit="km")
expanse(polylist[["pigs_core"]], unit="km")

# Moderate
expanse(polylist[["deer_moderate"]], unit="km")
expanse(polylist[["pigs_moderate"]], unit="km")

# Marginal
expanse(polylist[["deer_marginal"]], unit="km")
expanse(polylist[["pigs_marginal"]], unit="km")

## Calculate area overlap
# Core deer & core pig habitat overlap 
ovp1 <- terra::union(polylist$deer_core, polylist$pigs_core)
expanse(ovp1, unit="km")[[3]]

# Core deer & core pig habitat overlap - moderate
ovp2 <- terra::union(polylist$deer_moderate, polylist$pigs_moderate)
expanse(ovp2, unit="km")[[3]]

# Core deer & core pig habitat overlap - marginal
ovp3 <- terra::union(polylist$deer_marginal, polylist$pigs_marginal)
expanse(ovp3, unit="km")[[3]]


## How much deer core area in CWD zones?
# read CWD counties shapefile
cwd <- vect("data/landscape_data/2024CWDpositive_counties.shp")
cwd <- project(cwd, crs(polylist$deer_core))

cwd_deer_core <- crop(polylist$deer_core, cwd)   
expanse(cwd_deer_core, unit="km")  
  
cwd_deer_marg <- crop(polylist$deer_marginal, cwd)   
expanse(cwd_deer_marg, unit="km") 
  
#### Create patch plot for manuscript ####
## For each species, combine into multiclass raster (mean predictions)
# Will use the patch values to reclassify
patch_vals <- c(3,2,1)
patch_class <- c("Core", "Moderate", "Marginal")

## Mosaic rasters
deer_mn <- mosaic(patches["deer_marginal"], patches["deer_moderate"], fun = "sum")
deer_mn <- mosaic(deer_mn, patches["deer_core"], fun="sum")

pigs_mn <- mosaic(patches["pigs_marginal"], patches["pigs_moderate"], fun = "sum")
pigs_mn <- mosaic(pigs_mn, patches["pigs_core"], fun="sum")

writeRaster(pigs_mn, "data/landscape_data/pigs_suitability_levels.tif", overwrite=TRUE)
writeRaster(deer_mn, "data/landscape_data/deer_suitability_levels.tif", overwrite=TRUE)

## Reclassify
# Add patch types to raster
levels(deer_mn) <- list(data.frame(ID = patch_vals,
                                   patch = patch_class))

levels(pigs_mn) <- list(data.frame(ID = patch_vals,
                                   patch = patch_class))

### Read in region polygon
regions <- vect("data/landscape_data/ms_soil_ecoregions.shp")

# Assign names to polygons
regions <- regions |>
  mutate(name=c("Delta", "Interior Flatwoods", "Upper Coastal Plain", "Blackland Prairie", "Coastal Flatwoods",
                "Lower Coastal Plain", "Thin Loess", "Thick Loess"))

# Combine Thick and Thin Loess into just Loess
regions[["diss_id"]]<- c(2, 2, 2, 2, 2, 2, 1, 1)

# split
split_vectors <- split(regions, f = regions$diss_id)

# Dissolve the loess regions
split_vectors$`1` <- aggregate(split_vectors$`1`)

# Add name to dissolved loess
# values(split_vectors$`1`) <- "Loess"

# # drop all columns from the rest of the polygons (except region names)
split_vectors$`2` <- split_vectors$`2`["name"]

# Combine the list of SpatVectors back into a single SpatVector
regions <- rbind(split_vectors$`1`, split_vectors$`2`)

regions[["name"]] <- ifelse(is.na(regions$name), "Loess", regions$name)

ggplot(regions) +
  geom_spatvector(color="black", aes(fill=name))

writeVector(regions, "data/landscape_data/edited_ms_soil_regions.shp", overwrite=TRUE)

#### Plot ####
# Deer plot
deer_patches <- ggplot() +
  geom_spatraster(data=deer_mn, alpha=0.8) +
  scale_fill_viridis_d(option="D", direction=-1, name="Suitability Level", na.value="transparent", na.translate=FALSE) +
  geom_spatvector(data=ms, color="black", fill=NA, linewidth=0.4) +
  geom_spatvector(data=regions, color="black", fill=NA, linewidth=0.4) +
  theme_void() +
  annotation_north_arrow(
    which_north = TRUE,
    pad_x = unit(0.05, "npc"),
    pad_y = unit(0.75, "npc"),
    style = north_arrow_minimal()) 

# Pig plot
pig_patches <- ggplot() +
  geom_spatraster(data=pigs_mn, alpha=0.8) +
  scale_fill_viridis_d(option="D", direction=-1, name="Suitability Level", na.value="transparent", na.translate=FALSE) +
  geom_spatvector(data=ms, color="black", fill=NA, linewidth=0.4) +
  geom_spatvector(data=regions, color="black", fill=NA, linewidth=0.4) +
  theme_void() +
  annotation_scale(
    height = unit(0.015, "npc"),
    width_hint = 0.5,
    pad_x = unit(0.55, "npc"),
    pad_y = unit(0.01, "npc"),
    text_cex = .9) 

# Combine plot with patchwork
deer_patches + pig_patches +
  # plot_annotation(tag_levels = 'a', tag_prefix="(", tag_suffix=")") +
  plot_layout(guides = 'collect') & 
  theme(legend.position = 'bottom', 
        legend.text=element_text(size=11),
        legend.title=element_text(size=12))

# Save maps
ggsave(file="figs/Fig3_patches.svg")
# Saving 9.95 x 9 in image


## Determine average suitabiltiy(exclusive)

## read in RSF
deer_rsf <- rast("results/predictions/deer_rsf_predicted_90m.tif")
pig_rsf <- rast("results/predictions/pigs_rsf_predicted_90m.tif")

# Deer core
d_core <- mask(deer_rsf, polylist[["deer_core"]])
global(d_core, fun=mean, na.rm=TRUE)

# Deer moderate
d_moderate_only <- mask(deer_rsf, polylist[["deer_moderate"]])
d_moderate_only <- mask(d_moderate_only,  polylist[["deer_core"]], inverse = TRUE)
global(d_moderate_only, fun=mean, na.rm=TRUE)

# Deer marginal
d_marginal_only <- mask(deer_rsf, polylist[["deer_marginal"]])
d_marginal_only <- mask(d_marginal_only,  polylist[["deer_moderate"]], inverse = TRUE)
global(d_marginal_only, fun=mean, na.rm=TRUE)


# Pig core
p_core <- mask(pig_rsf, polylist[["pigs_core"]])
global(p_core, fun=mean, na.rm=TRUE)

# Deer moderate
p_moderate_only <- mask(pig_rsf, polylist[["pigs_moderate"]])
p_moderate_only <- mask(p_moderate_only,  polylist[["pigs_core"]], inverse = TRUE)
global(p_moderate_only, fun=mean, na.rm=TRUE)

# Deer marginal
p_marginal_only <- mask(pig_rsf, polylist[["pigs_marginal"]])
p_marginal_only <- mask(p_marginal_only,  polylist[["pigs_moderate"]], inverse = TRUE)
global(p_marginal_only, fun=mean, na.rm=TRUE)