## This script reads in ASCII rasters generated by RAMAS spatial data and creates a plot

library(tidyverse)
library(terra)
library(tidyterra)
library(patchwork)
library(ggspatial)

# Read in MS shapefile
ms <- vect("data/landscape_data/mississippi_ACEA.shp")

# List patch .asc files
patches <- list.files(path="results/exported_patches/", pattern=".ASC", full.names=TRUE)  # note that the pattern argument is case-sensitive, and RAMAS writes ASCII files as .ASC instead of .asc like R

# grab 1 set per species
patches <- patches[str_detect(patches, "2")]

# Make raster "stack"
patches <- rast(patches)

# Define projection
crs(patches) <- crs(ms)

# Reclassify so that 0 becomes NA (backround is 0, patches are numbered starting with 1), and all patches receive same class value (1)
# If you want to show different patches, don't do the second part
# Replace 0 with NA
patches <- ifel(patches == 0, NA_integer_, patches)

# Loop over patches and write as .tif
for (i in 1:dim(patches)[3]) {
  # Subset to each layer
  patch <- patches[[i]]
  
  # create filename
  filename <- paste0("results/exported_patches/", names(patch), ".tif")
  
  # write raster
  writeRaster(patch, filename, overwrite=TRUE)
}
# Reclassify all patches as 1
patches <- ifel(patches>=1, 1, patches)

# Convert rasters to polygons
polylist <- lapply(as.list(patches), as.polygons)

# Make a named list so layers can by extracted by name
names(polylist) <- names(patches)

## Calculate area
area_deer <- expanse(polylist[["deer_core_22_patch"]], unit="km")
area_pigs <- expanse(polylist[["pigs_core_27_patch"]], unit="km")

# Core deer & core pig habitat overlap 
ovp1 <- terra::union(polylist$deer_core_22_patch, polylist$pigs_core_27_patch)
expanse(ovp1, unit="km")[[3]]



#### Create patch plot for manuscript ####
## For each species, combine into multiclass raster (mean predictions)
# Will use the patch values to reclassify
patch_vals <- c(3,2,1)
patch_class <- c("Core", "Marginal", "Highly Marginal")

## Mosaic rasters
deer_mn <- mosaic(patches["deer_highlymargina_22_patch"], patches["deer_marginal_22_patch"], fun = "sum")
deer_mn <- mosaic(deer_mn, patches["deer_core_22_patch"], fun="sum")

pigs_mn <- mosaic(patches["pigs_highlymarginal_27_patch"], patches["pigs_marginal_27_patch"], fun = "sum")
pigs_mn <- mosaic(pigs_mn, patches["pigs_core_27_patch"], fun="sum")

## Reclassify
# Add patch types to raster
levels(deer_mn) <- list(data.frame(ID = patch_vals,
                                   patch = patch_class))

levels(pigs_mn) <- list(data.frame(ID = patch_vals,
                                   patch = patch_class))

## Plot
deer_patches <- ggplot() +
  geom_spatraster(data=deer_mn) +
  scale_fill_viridis_d(option="D", direction=-1, name="Patch Type:", na.value="transparent", na.translate=FALSE) +
  geom_spatvector(data=ms, color="black", fill=NA, linewidth=0.4) +
  theme_void() +
  annotation_north_arrow(
    which_north = TRUE,
    pad_x = unit(0.05, "npc"),
    pad_y = unit(0.85, "npc"),
    style = north_arrow_minimal()) 

pig_patches <- ggplot() +
  geom_spatraster(data=pigs_mn) +
  scale_fill_viridis_d(option="D", direction=-1, name="Patch Type:", na.value="transparent", na.translate=FALSE) +
  geom_spatvector(data=ms, color="black", fill=NA, linewidth=0.4) +
  theme_void() +
  annotation_scale(
    height = unit(0.015, "npc"),
    width_hint = 0.5,
    pad_x = unit(0.55, "npc"),
    pad_y = unit(0.01, "npc"),
    text_cex = .9) 

deer_patches + pig_patches +
  # plot_annotation(tag_levels = 'a', tag_prefix="(", tag_suffix=")") +
  plot_layout(guides = 'collect') & 
  theme(legend.position = 'bottom', 
        legend.text=element_text(size=11),
        legend.title=element_text(size=12))

ggsave(file="figs/Fig4_patches.svg")
# 10.4 x 9 in image